<?PHP
   
   // set the current version
   Settings::set( 'cms', 'templates', array(
      
      // available templates for menu items
      'menuitem' => array(
         'cms.articles.standard'           => 'Standard Article Listing',
         'cms.articles.standard_wide'      => 'Wide Article Listing (with menu)',
         'cms.articles.menu-span-20-blank' => 'Blank span-20 with menu',
         'cms.articles.quarantine'         => 'Special Article Quarantine',
         'cms.products.list'               => 'Standard Product Listing',
         'cms.products.1big+8medium+list'  => '1 Big, 8 Medium Listing',
         'cms.products.8medium+list'       => '8 Medium Listing',
         'cms.mainpages.products'          => 'Products Main Page',
          'cms.mainpages.produkter'          => 'Producter Hovudside 2018',
         'cms.mainpages.frontpage'         => 'Site frontpage',

         // product categories
         'cms.products.category'           => 'Product Category',
         'cms.products.categories_2column' => 'Product Categories 2 column',
         'cms.products.calendars'          => 'Category: Calendars',
         'cms.products.photo-books'        => 'Category: Photo books',
         'cms.products.photo-gifts'        => 'Category: Photo gifts',
         'cms.products.cards'              => 'Category: Cards',
         'cms.products.photocards'         => 'Category: Fotokort2018Fotono',
          'cms.products.fotokort'         => 'Category: Fotokort2018Eurofoto',
         'cms.products.canvas'             => 'Category: Canvas',
         'cms.products.enlargements'       => 'Category: Enlargements',
         'cms.products.accessories'        => 'Category: Accessories',
         'cms.products.scrapbook'          => 'Category: Scrapbook',
         'cms.products.ukeplan'            => 'Category: Ukeplan',
         'cms.products.monthplan'          => 'Category: Månedplan',
       'cms.products.refleksproducts'    => 'Refleksprodukter',
         'cms.products.photofolder'        => 'Fotohefte',
       
         
          'cms.products.tshirts'          => 'tshirts',
           'cms.products.sognogfjordanebulk'          => 'Sogn og Fjordane Bulk',
            'cms.products.katalogar'          => 'Repix Katalogar',
        'cms.products.mediaclip'          => 'Mediaclip Lerret',
        'cms.products.mediaclip_3col'     => '3 Bootstrap Kol',
         'cms.products.mediaclip_4col'    => '4 Bootstrap Kol',
          'cms.products.mediaclip_split'=> 'Mediaclip 2 Split',  
           'cms.products.fotono_3bootstrap'=> 'Fotono With 3 bootsrtap',
        'cms.products.mediaclip_photobook'=> 'Mediaclip Fotobok',
        'cms.products.mediaclip_premium_photobook'=> 'Mediaclip Premium Fotobok',
        'cms.products.mediaclip_standard_photobook'=> 'Mediaclip Standard Fotobok',
        'cms.products.mediaclip_softcover'=> 'Mediaclip Softcover',
        'cms.products.hardcover_photobook'=> 'Mediaclip Hardcover',
        'cms.products.mediaclip_poster'   => 'Mediaclip poster',
        'cms.products.mediaclip_canvas'   => 'Mediaclip canvas',
        'cms.products.mediaclip_chromalux'=> 'Mediaclip chromalux',
        'cms.products.mediaclip_etiketter'   => 'Mediaclip Etiketter',
        'cms.products.mediaclip_metallic_paper'   =>'Mediaclip Metallic Paper',
        'cms.products.mediaclip_lyskasse'   => 'Mediaclip Lyskasse',
        'cms.products.mediaclip_produkt'   => 'Mediaclip Produkt',
        'cms.products.mediaclip_glass'   => 'Mediaclip Glass',
        'cms.products.mediaclip_lyskasse'   => 'Mediaclip Tonerose',
        'cms.products.mediaclip_calenders'   => 'Mediaclip Kalendere',
        'cms.products.mediaclip_kopper'   => 'Mediaclip Kopper',
        'cms.products.mediaclip-splitcanvas'   => 'Mediaclip Split Canvas',
        'cms.products.gifting'             => 'Gaver 2 kolonner',
        'cms.products.ukeplangavekort'     => 'Gavekort Ugeplan',
         'cms.products.ukeplan'            => 'Category: Ukeplan',
         'cms.products.piktogrammer'       => 'Category: Piktogrammer',
         'cms.products.dagplan'            => 'Category: Dagplan',
         'cms.products.ukeplanmagnet'      => 'Category: Magnet',
         'cms.products.ugeplanmedfigurer'  => 'Category: Figurer',
         'cms.products.monthplan'          => 'Category: Månedplan',
         'cms.products.dorskilt'           => 'Category: Dørskilt',
         'cms.products.skilter'            => 'Category: Skilter',
         'cms.products.giftcard'           => 'Category: Gavekort',
         
         'cms.products.subcategory'        => 'Product Sub-category',
         'cms.products.list'               => 'Product list',
         'cms.products.list-show-first'    => 'Product list, show first product',
         'cms.products.list-no-from-price' => 'Product list without from-price',
         'cms.products.photo_books'        => 'Photo Books',
         'cms.products.cewe_photo_books'   => 'Cewe Photo Books',
         'cms.products.cewe_photo_books_download'   => 'Cewe Photo Books Download',
         'cms.products.spesial-print'      => 'Spesial print',
         'cms.products.span-24_with_product_list' => 'Wide article with product',
         'cms.mainpages.tips-and-tricks'   => 'Tips & Tricks - Mainpage',
         'cms.mainpages.faq'               => 'FAQpage',
         'cms.mainpages.contact'           => "Contact",
         'cms.products.blank_span-20'      => 'Blank span-20',
         'cms.products.blank_span-24'      => 'Blank span-24',
         'cms.products.christmas'          => 'Christmas',
         'cms.products.christmas-card'     => 'Christmas Card',
         'cms.products.ukens-tilbud'       => 'Ukens tilbud',
         'cms.products.articlecategory'    => 'Article category',
         'cms.products.article-body-only'  => 'Article Body Only',
         'cms.products.camera-redirect'    => 'Camera redirect',
         'cms.products.brodering'          => 'Brodering',
         'cms.products.refleksvest'        => 'Refleksvest',
         'cms.functions.brydeg'           => 'Bry deg',
         'cms.functions.contest'           => 'Contest',
         'cms.functions.calendar'          => 'Calendar',
         'cms.functions.dyreparken_barcode'=> 'Dyreparken barcode',
         'cms.functions.one-image-mutiple-products' => 'Order one image on multiple products',
         'cms.functions.takkekort-med-video' => "Takkekort med video",
         
         
         'cms.themes.christmas' => "Christmas Theme",
         'cms.themes.morsday_and_valentine' => "Mothersday and Valentine Theme",
         'cms.themes.love' => "Love Theme",
         'cms.themes.wedding' => "Wedding Theme",
         'cms.themes.birthday' => "Birthday Theme",
         'cms.themes.dap' => "Dåp Theme",
         'cms.themes.konfirmasjon' => "Konfirmasjon Theme",
         'cms.themes.baby' => "Baby Theme",
         'cms.themes.alle' => "All Themes",
         'cms.themes.accessories' => "Accessories Themes",
         'cms.themes.bordkort' => "Bordkort Themes",
         'cms.themes.menykort' => "Menykort Themes",
      ),
      
      // available templates for content entities
      'textentity' => array(
         'cms.content'                     => 'Default Content Rendering',
         'cms.articles.standard'           => 'Article Rendering',
         'cms.products.show_one_product'   => 'Product Page Rendering',
         'cms.products.textproduct'        => 'Text product',
         'cms.products.flaskeproduct'        => 'Flaske product',
         'cms.products.refleksvest'        => 'Refleksvest',
         'cms.articles.photo_books'        => 'Photo Books'
      ),
      
      // setup some defaults for new objects
      'textentity_defaults' => array(
         'article' => 'cms.articles.standard',
         'product' => 'cms.products.show_one_product',
      ),
      
   ) );
   
?>
