#!/usr/bin/php -q
<?PHP
   
   // bootstrap the platform
   chdir( dirname( __FILE__ ) ); include '../../bootstrap.php';
   
   // configure the platform for CLI
   config( 'website.config' );
   import( 'system.cli' );
   
   // import required classes
   import( 'math.zbase32' );
   import( 'website.album.identifier' );
   library( 'jpgraph.jpgraph_barcode' );
   
   class BarcodeArchiveGenerator extends Script {
      
      public function Main( $argc = 0, $argv = array() ) {
         
         if( $argc < 3 ) {
            
            echo "Usage: generatebarcodes.php <batchid> <outputfile.zip>\n";
            
         } else {
            
            $batchid = (int) $argv[1];
            $zipname = $argv[2];
            
            $zip = new ZipArchive();
            $zip->open( $zipname, ZIPARCHIVE::CREATE | ZIPARCHIVE::OVERWRITE );
            $zip->setArchiveComment( 'barcode archive generated by eurofoto.no' );
            
            $albumidentifier = new AlbumIdentifier();
            $items = $albumidentifier->collection( array( 'id', 'identifier' ), array( 'batchid' => $batchid ) );
            
            echo sprintf( "Creating archive %s of %d items from batch #%d...\n", $zipname, $items->count(), $batchid );
            
            $encoder = BarcodeFactory::Create( ENCODING_CODE128 );
      		$encoder->AddChecksum( false );
				
      		$eps = BackendFactory::Create( BACKEND_PS, $encoder );
				$eps->SetEPS();
				$eps->AddChecksum( true );
      		$eps->SetHeight( 70 );
      		$eps->SetVertical( false );
      		$eps->SetModuleWidth( 2 );
      		$eps->SetScale( 1 );
      		$eps->HideText( true );
      		
      		$buffer = "\"code\",\"@barcode\",\"mobilecode\"\n";
            
            while( list( $id, $identifier ) = $items->fetchRow() ) {
               
               $mobilecode = strtoupper( substr( $identifier, 0, 4 ).str_pad( zBase32::encode( $id ), 3, '0', STR_PAD_LEFT ) );
               if( isset( $mobilecodes[$mobilecode] ) ) {
                  echo 'D';
               } else {
                  $mobilecodes[$mobilecode] = true;
               }
               
               $zip->addFromString( 'eps-'.$batchid.'/'.$identifier.'.eps', $eps->Stroke( $identifier ) );
               $buffer .= "\"$identifier\",\"eps-".$batchid."/$identifier.eps\",\"$mobilecode\"\n";
               if( ++$i % 100 == 0 ) echo '.';
               
            }
            
            $zip->addFromString( sprintf( 'index-%d.csv', $batchid ), $buffer );
            
            $zip->close();
            
            echo "\nOK.\n";
            
         }
         
      }
      
   }
   
   CLI::Execute();
   
?>
