<?PHP


   Settings::SetSection( 'domainMap', array(
         'fotoclick.eurofoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-FOTOALMENNING',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 0,
               'title'     => 'Foto Almenning',
               'adresse'   => "Nordstrandsvegen 13",
               'postnr'    => '6823',
               'poststed'  => 'Sandane',
               'logo'      => 'logo_allmenning.jpg',
               'homepage'  => 'foto-almenning.no',
               'contactpage' => 'http://www.foto-almenning.no/kontakt.php?language=no',
               'phone'     => '57 86 56 33',
               'email'     => 'post@foto-almenning.no',
               'orgnr'     => '952 190 202 MVA'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.foto-almenning.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-FOTOALMENNING',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 0,
               'title'     => 'Foto Almenning',
               'adresse'   => "Nordstrandsvegen 13",
               'postnr'    => '6823',
               'poststed'  => 'Sandane',
               'logo'      => 'logo_allmenning.jpg',
               'homepage'  => 'foto-almenning.no',
               'contactpage' => 'http://www.foto-almenning.no/kontakt.php?language=no',
               'phone'     => '57 86 56 33',
               'email'     => 'post@foto-almenning.no',
               'orgnr'     => '952 190 202 MVA'
               
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.herheimfoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-HERHEIMFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 1,
               'title'     => 'Herheim Foto',
               'adresse'   => "Vangsgt. 46",
               'postnr'    => '5702',
               'poststed'  => 'Voss',
               'logo'      => 'logo_herheim.jpg',
               'homepage'  => 'herheimfoto.no',
               'contactpage' => 'http://www.herheimfoto.no/kontakt.php?language=no',
               'phone'     => '56 51 19 09',
               'email'     => 'post@herheimfoto.no',
               'orgnr'     => '980 646 475 MVA'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      /*'nettbutikk.arfoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-ARFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 2,
               'title'     => 'AR FOTO AS',
               'adresse'   => "Kinogata 2",
               'postnr'    => '2850',
               'poststed'  => 'Lena',
               'logo'      => 'logo_arfoto.jpg',
               'homepage'  => 'arfoto.no',
               'contactpage' => 'http://www.arfoto.no/kontakt.php?language=no',
               'phone'     => '61 16 16 00',
               'email'     => 'post@arfoto.no',
               'orgnr'     => '994269100'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),*/
      'nettbutikk.arilfoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-ARILFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 3,
               'title'     => 'Aril Foto',
               'adresse'   => "Storgt. 14",
               'postnr'    => '1890',
               'poststed'  => 'Rakkestad',
               'logo'      => 'logo_arilfoto.jpg',
               'homepage'  => 'arilfoto.no',
               'contactpage' => 'http://www.arilfoto.no/kontakt.php?language=no',
               'phone'     => '69 22 13 40',
               'email'     => 'rakkestad@fotoclick.no',
               'orgnr'     => '948 851 881 MVA'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.fotobirkeland.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-BIRKELAND',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 4,
               'title'     => 'E. Birkeland AS',
               'adresse'   => "MoldeTorget",
               'postnr'    => '6413',
               'poststed'  => 'Molde',
               'logo'      => 'logo_birkeland.jpg',
               'homepage'  => 'fotobirkeland.no',
               'contactpage' => 'http://www.molde.fotoclick.no/kontakt.php?language=no',
               'phone'     => '71 21 94 50',
               'email'     => 'post@fotobirkeland.no',
               'orgnr'     => '910 590 618 MVA'
            ),
         ),
         'redirect'      => 'http://www.godebilder.no',
         'https'         => false,
      ),
      'nettbutikk.gol.fotoclick.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-SKREDEGAARD',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 5,
               'title'     => 'Skredegård Foto AS',
               'adresse'   => "Sentrumsvn. 104, pb. 144",
               'postnr'    => '3551',
               'poststed'  => 'Gol',
               'logo'      => 'logo_skredegaard.jpg',
               'homepage'  => 'gol.fotoclick.no',
               'contactpage' => 'http://www.gol.fotoclick.no/kontakt.php?language=no',
               'phone'     => '32 07 40 95',
               'email'     => 'bilder@skredegaard-foto.no',
               'orgnr'     => '947 100 033 MVA'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.svolvaer.fotoclick.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-HASSELBERG',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 6,
               'title'     => 'Foto Hasselberg',
               'adresse'   => 'Torget 14',
               'postnr'    => '8300',
               'poststed'  => 'Svolvær',
               'logo'      => 'logo_hasselberg.jpg',
               'homepage'  => 'svolvaer.fotoclick.no',
               'contactpage' => 'http://www.svolvaer.fotoclick.no/kontakt.php?language=no',
               'phone'     => '76 07 19 10',
               'email'     => 'svolvaer@fotoclick.no',
               'orgnr'     => '954 670 775 MVA'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.joarfoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-JOARFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 7,
               'title'     => 'Joar Foto',
               'adresse'   => 'Storgt. 4',
               'postnr'    => '1440',
               'poststed'  => 'Drøbak',
               'logo'      => 'logo_joarfoto.jpg',
               'homepage'  => 'joarfoto.no',
               'contactpage' => 'http://www.joarfoto.no/kontakt.php?language=no',
               'phone'     => '+47 64 93 21 28',
               'email'     => 'joarfoto@online.no',
               'orgnr'     => '955 685 164 MVA'
            ),
         ),
         'redirect'      => 'http://www.joarfoto.no',
         'https'         => false,
      ),
      'nettbutikk.knips.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-KNIPSFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 8,
               'title'     => 'Knips AS',
               'adresse'   => 'Kongens gate 37',
               'postnr'    => '7713',
               'poststed'  => 'Steinkjer',
               'logo'      => 'logo_knips.jpg',
               'homepage'  => 'knips.no',
               'contactpage' => 'http://www.knips.no/kontakt.php?language=no',
               'phone'     => '74 16 32 50',
               'email'     => 'post@knips.no',
               'orgnr'     => '942519192'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.gallerigalaen.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-GALLERRIGALAEN',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 9,
               'title'     => 'Galleri Galåen',
               'adresse'   => 'Kjerkgt. 8',
               'postnr'    => '7374',
               'poststed'  => 'Røros',
               'logo'      => 'logo_galaaen.jpg',
               'homepage'  => 'gallerigalaen.no',
               'contactpage' => 'http://www.gallerigalaen.no/kontakt.php?language=no',
               'phone'     => '72 41 15 69',
               'email'     => 'roeros@fotoclick.no',
               'orgnr'     => '951 509 574 MVA'
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.aasfoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-AASFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 10,
               'title'     => 'Ås Foto',
               'adresse'   => 'Moerveien 6',
               'postnr'    => '1430',
               'poststed'  => 'Ås',
               'logo'      => 'logo_aasfoto.jpg',
               'homepage'  => 'aasfoto.no',
               'contactpage' => 'http://www.aasfoto.no/Kontakt',
               'phone'     => '64 94 12 41',
               'email'     => 'epost@aasfoto.no',
               'orgnr'     => ''
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.fotolabben.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-FOTOLABBEN',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 11,
               'title'     => 'Fotolabben Moss',
               'adresse'   => 'Carlbergveien 2',
               'postnr'    => '1526',
               'poststed'  => 'Moss',
               'logo'      => 'logo_fotolabben.jpg',
               'homepage'  => 'fotolabben.no',
               'contactpage' => '#',
               'phone'     => '69 26 20 18',
               'email'     => 'post@fotolabben.no',
               'orgnr'     => ''
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.lyshol.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-LYSHOL',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 12,
               'title'     => 'Fotograf P.P. Lyshol',
               'adresse'   => 'Aure',
               'postnr'    => '6230',
               'poststed'  => 'Sykkylven',
               'logo'      => 'logo_pplysholm.jpg',
               'homepage'  => 'lyshol.no',
               'contactpage' => '#',
               'phone'     => '70 25 10 27',
               'email'     => 'post@lyshol.no',
               'orgnr'     => ''
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
     'netbutikk.stathellefoto.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-STATHELLE',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 13,
               'title'     => 'Stathelle Foto',
               'adresse'   => 'Gangveien 10',
               'postnr'    => '3960',
               'poststed'  => 'Stathelle ',
               'logo'      => 'logo_stathelle.jpg',
               'homepage'  => 'stathellefoto.no',
               'contactpage' => '#',
               'phone'     => '35 97 33 50',
               'email'     => 'post@stathellefoto.no',
               'orgnr'     => '997015940 '
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
      'nettbutikk.agfotohalden.no' => array(
         'siteroot'      => 'website',
         'template'      => 'fotoclick',
         'language'      => 'nb_NO',
         'portal'        => 'FC-001',
         'logingroup'    => 'FC-AGFOTO',
         'fallback'      => 'eurofoto',
         'siteid'        => 1,
         'customattr'    => array(
            'countryid'  => 160,
            'portalid'   => 25,
            'lyrishq'    => '',
            'google'     => array(
               'analytics'                 => '',
               'google-site-verification'  => '',
            ),
            'login' => array(
               'bytoken' => '/bestill-ett-bilde',
            ),
            'fotoclick' => array(
               'id'        => 14,
               'title'     => 'AG Foto AS',
               'adresse'   => 'Torget 1',
               'postnr'    => '1767',
               'poststed'  => 'HALDEN ',
               'logo'      => 'logo_agfoto.jpg',
               'homepage'  => 'agfotohalden.no',
               'contactpage' => 'http://agfotohalden.no/kontakt.php',
               'phone'     => '69 18 82 60',
               'email'     => 'agfoto@halden.net',
               'orgnr'     => ''
            ),
         ),
         'redirect'      => false,
         'https'         => false,
      ),
   ) );


?>